- source.lua
Optimizing and improving code performance
> Release 1.4

- source.lua
Optimizing and improving code performance
> Release 1.4.3

- source.lua
> Release 1.4.4

- source.lua
> Release 1.4.5

- source.lua
> Release 1.4.7

- source.lua
> Release 1.4.8

- source.lua
> Release 1.4.9

- source.lua
Implemented ability to view player's team colours.
> Team Colour

- source.lua
Improved accuracy of the Aimbot by favoring targets which are closer to the mouse.
> Closest to Mouse

- source.lua
> Random Aim Part Option

- source.lua
> Release 1.7.2

- source.lua
> Release 1.7.3

- source.lua
> Release 1.7.4

- source.lua
> Release 1.7.5

- README.md
- source.lua
Performance Improvement. Static & Dynamic Offset
> Release 1.7.7

- source.lua
> Release 1.7.8

- README.md
- source.lua
> Release 1.7.9

- README.md
- source.lua
> Release 1.7.10

- source.lua
> Release 1.8.3

- source.lua
Added Chance Calculation for "Mouse.Hit / Mouse.Target" Method
> Release 1.8.5

- source.lua
> Release 1.8.6

- source.lua
> Release 1.8.7

- source.lua
> Release 1.8.8

- source.lua
> Release 1.8.9

- source.lua
> Release 1.8.10

- source.lua
> Release 1.8.11

- source.lua
> Release 1.8.12

- source.lua
> Release 1.8.13

- README.md
- source.lua
> Release 1.8.14

- source.lua
> Release 1.8.16

- source.lua
Improved Configuration Manager
> Release 1.8.17

- source.lua
> Release 1.8.18

- source.lua
> Release 1.8.19

- source.lua
Added Configuration Manager Paragraph
> Release 1.8.20

- source.lua
> Release 1.8.21

- README.md
- source.lua
Completed the Global Update for the Free Version
> Release 1.9

- source.lua
> Release 1.9.1

- README.md
- source.lua
Global Update for the Free Version
> Release 1.9.2

- source.lua
> Release 1.9.3

- source.lua
> Release 1.9.4
